# Generated by Django 4.0.4 on 2022-09-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0005_alter_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tryes',
            field=models.CharField(max_length=12),
        ),
    ]
