# Generated by Django 4.0.4 on 2022-09-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0006_alter_game_tryes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='tryes',
            new_name='attempts',
        ),
    ]
