# Generated by Django 4.0.4 on 2022-09-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0007_rename_tryes_game_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rightAttempts',
            field=models.CharField(default='2', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='attempts',
            field=models.CharField(max_length=4),
        ),
    ]
