# Generated by Django 4.0.4 on 2022-09-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0008_game_rightattempts_alter_game_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='wrongAttempts',
            field=models.CharField(default='3', max_length=4),
            preserve_default=False,
        ),
    ]
